server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip para comprimir los archivos enviados al cliente
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Solución estricta para el enrutador de Vue (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Caché estricta para archivos estáticos inmutables (rendimiento)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}